#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/platform-modules-e582-48x6q" ]; then
	update-rc.d platform-modules-e582-48x6q defaults >/dev/null
	invoke-rc.d platform-modules-e582-48x6q start || exit $?
fi
# End automatically added section
# Automatically added by dh_installmodules
if [ "$1" = "configure" ]; then
	if [ -e /boot/System.map-3.16.0-5-amd64 ]; then
		depmod -a -F /boot/System.map-3.16.0-5-amd64 3.16.0-5-amd64 || true
	fi
fi
# End automatically added section
